## Ursprung und Datenerhebung

Die Daten des Netzwerks wurden von den Webseiten und Jahresberichten der Mitglieder des WASH-Netzwerks erhoben. Aussortiert wurden dabei NGOs, die Isolates sind und somit mit keiner anderen NGO verbunden.

## EDGE-Attribute
FROM
Name der Person, nur Nachname. Falls der Name populär ist oder öfters vorkommt, wird der erste Buchstabe des Vornamens hinzugefügt z.B. Mueller oder MuellerH

TO
NGO aus dem WASH-Netzwerk. Hierbei muss sich an der Liste der NGO-Abkürzungen orientiert werden (siehe unten).

## NODE-Attribute
ID
Nachname der Person. Falls der Name populär ist oder öfters vorkommt, wird der erste Buchstabe des Vornamens hinzugefügt. An der Edgelist orientieren

NAME
Nachname der Person. Falls der Name populär ist oder öfters vorkommt, wird der erste Buchstabe des Vornamens hinzugefügt.

nameall
Ausgeschriebener Name mit Leerzeichen zwischen Vor- und Nachname.

SEX
1 = männlich (rechteck)
2 = weiblich (kreis)
3 = kein Geschlecht (NGOs) (kreis)

DERZEITIGENGO
Die derzeitige NGO, in der die Person tätig ist. An der Liste NGO Abkürzungen orientieren.

PARTEI
1 = CDU - pink
2 = CSU - hellblau
3 = SPD - rot
4 = Bündnis 90 Grünen - grün
5 = FDP - gelb
6 = Die Linke - lila
7 = NGO - grau
8 = Keine Partei - orange

## LISTE NGO-Abkürzungen

ADRA,Adventistische Entwicklungs- und Katastrophenhilfe ADRA Deutschland e. V.;
am,action Medeor;
arche,arche noVa;
ASB,Arbeiter-Samariter-Bund;
BORDA,BORDA;
care,care;
cbm,Christoffel Blindenmission;
DAHW,Deutsche Lepra- und Tuberkulosehilfe e.V.;
GTO,German Toilet Organization;
help,HELP - Hilfe zur Selbsthilfe;
IOG,Ingenieure ohne Grenzen;
JU,Johanniter Unfallhilfe e.V; 
MI,Malteser International;
PD,Plan Deutschland;
ToG,Tierärzte ohne Grenzen;
VcA,Viva con Agua;
WECF,Women Engage For A Common Future e.V.; 
WHH,Welthungerhilfe;
WIN,Water Integrity Network;
WRD,world relief Deutschland;
WU,Wash United; 
WV,World Vision;
