## Ursprung und Datenerhebung

wip

## EDGE-Attribute
FROM
Name der Person, nur Nachname. Falls der Name populär ist oder öfters vorkommt, wird der erste Buchstabe des Vornamens hinzugefügt z.B. Mueller oder MuellerH

TO
NGO aus dem WASH-Netzwerk. Hierbei muss sich an der Liste der NGO-Abkürzungen orientiert werden.

## NODE-Attribute
ID
Nachname der Person. Falls der Name populär ist oder öfters vorkommt, wird der erste Buchstabe des Vornamens hinzugefügt. An der Edgelist orientieren

NAME
Ausgeschriebener Name mit Leerzeichen zwischen Vor- und Nachname-

SEX
1 = männlich (rechteck)
2 = weiblich (dreieck)
3 = kein Geschlecht (NGOs) (kreis)

POSITION
Nur männliche Form: Präsident (rot/red), Vizepräsident (orange), Präsidium (gelb/yellow), Kuratorium (grün/green), Vorstand (hellblau/lightblue), Bundesvorstand (dunkelblau/blue), Verwaltungsrat (lila/purple),  Beirat (pink), Aufsichtsrat (braun/brown), NGO (grau)

DERZEITIGENGO
Die derzeitige NGO, in der die Person tätig ist. An der Liste NGO Abkürzungen orientieren

PARTEI
1 = CDU - schwarz
2 = CSU - blau
3 = SPD - rot
4 = Bündnis 90 Grünen- grün
5 = FDP - gelb
6 = Die Linke - lila
7 = NGO - grau
8 = Keine Partei - weiß

## LISTE NGO-Abkürzungen

ADRA,Adventistische Entwicklungs- und Katastrophenhilfe ADRA Deutschland e. V.;
am,action Medeor;
arche,arche noVa;
ASB,Arbeiter-Samariter-Bund;
BORDA,BORDA;
care,care;
cbm,Christoffel Blindenmission;
DAHW,Deutsche Lepra- und Tuberkulosehilfe e.V.;
GTO,German Toilet Organization;
help,HELP - Hilfe zur Selbsthilfe;
IOG,Ingenieure ohne Grenzen;
JU,Johanniter Unfallhilfe e.V; 
MI,Malteser International;
PD,Plan Deutschland;
ToG,Tierärzte ohne Grenzen;
VcA,Viva con Agua;
WECF,Women Engage For A Common Future e.V.; 
WHH,Welthungerhilfe;
WIN,Water Integrity Network;
WRD,world relief Deutschland;
WU,Wash United; 
WV,World Vision;
